# In this notebook we are going to cover some of the most fundamentals of tensorflow using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function (a way to speed up your regular python functions)
* Using GPUs with TensorFlow(or TPUs)
* Exercises to try for yourself!

## Introduction to Tensors

In [61]:
# Import tensorflow
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.12.0


In [31]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [32]:
# Check the number of dimensions in tensor
scalar.ndim

0

In [33]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [34]:
# check the dimension of vector
vector.ndim

1

In [35]:
# create a matrix
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [36]:
matrix.ndim

2

In [37]:
# create another matrix
another_matrix =tf.constant([[10., 7.],
                   [3., 4.],
                   [8., 9.]], dtype=tf.float16) #specify the datatype with dtype
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  4.],
       [ 8.,  9.]], dtype=float16)>

In [38]:
another_matrix.shape

TensorShape([3, 2])

In [39]:
another_matrix.ndim

2

In [40]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6,]],
                      [[7, 8, 9],
                       [10,11,12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [41]:
tensor.ndim

3

what we've created so far:

* Scalar: a single number
* Vector: a number with direction(e.g. wind speed and direction)
* Matrix: a 2-Dimensional array of numbers
* Tensors: a n-dimensional array of numbers(when n can be any number, 0-dimensional tensor is a scalar, a 1- dimensional tensor is a vector)

###  Creating Tensors with tf.variable

In [42]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [9]:
# creating the same tensors with tf.variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [43]:
# Let's try change one of the elemnts with assign
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [44]:
# trying to change the elements in our unchangeable tensors
unchangeable_tensor[0].assign(7)

AttributeError: ignored

**Note** : Rarely  in practice you will need to decide whether to use `tf.constant` or `tf.variable` to create tensors , as TensorFlow does this for you.
However, if in doubt, use `tf.constant` and change it later if needed.

### Creating random tensors

Random tensors are tensors  of some arbitrary size which contain random numbers

In [45]:
# Create random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in tensor

In [19]:
# Shuffle a tensot(valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10, 4, 7],
                           [3, 4,4],
                            [2, 4, 5]])
# shuffle our not_shuffled
tf.random.set_seed(32)
shuffled = tf.random.shuffle(not_shuffled, seed= 32)
shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  4,  5],
       [ 3,  4,  4],
       [10,  4,  7]], dtype=int32)>

In [20]:
not_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  4,  7],
       [ 3,  4,  4],
       [ 2,  4,  5]], dtype=int32)>

### Exercise and perform some random variable(to-do)

In [46]:
tf.random.set_seed(42) # global level
shuffled = tf.random.shuffle(not_shuffled, seed= 42) # operational level random seed

### Other ways to make tensors

In [47]:
# create a  tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create a tensor of all zeroes
tf.zeros([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU(much faster for numerical computing)

In [ ]:
# Numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)#create numpy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for vector
# y = tf.constant(vector) #non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape =(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

## Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or Dimension
* Size

In [ ]:
# create a rank 4 tensor(4dimension)
rank_tensor4 = tf.zeros(shape=[2,3,4,5])
rank_tensor4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_tensor4[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_tensor4.shape, tf.size(rank_tensor4), rank_tensor4.ndim

(TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>, 4)

In [ ]:
# Get various attributes of our tensors
print("Datatype of every element:", rank_tensor4.dtype)
print("Number of Dimension(rank):", rank_tensor4.ndim)
print("Shape of tensor:", rank_tensor4.shape)
print("Elements along the 0 axis:", rank_tensor4.shape[0])
print("Elements along the last axis:", rank_tensor4.shape[-1])
print("Total numbers of elements in our tensor:" , tf.size(rank_tensor4).numpy())


Datatype of every element: <dtype: 'float32'>
Number of Dimension(rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total numbers of elements in our tensor: 120


### Indexing tensors
Tensors can be indexed just like the Python lists

In [ ]:
# Get the first 2 elements od each simension
rank_tensor4[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each  dimension from each index except for the final one
rank_tensor4[:1,:1,:1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#  Create a rank2 dimension
rank_2tensor = tf.constant([[1,2],
                            [4,5]])
rank_2tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

In [ ]:
rank_2tensor.ndim,  rank_2tensor.shape

(2, TensorShape([2, 2]))

In [ ]:
# Get the last item of each row of our rank 2 tensor
rank_2tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank3_tensor = rank_2tensor[..., tf.newaxis]
rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[4],
        [5]]], dtype=int32)>

In [ ]:
rank3_tensor.ndim


3

In [ ]:
# Alternate to tf.newaxis
tf.expand_dims(rank_2tensor, axis=(-1)) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[4],
        [5]]], dtype=int32)>

In [ ]:
rank_2tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2tensor, axis=0) #expand the 0-axis


<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [4, 5]]], dtype=int32)>

## Manipulating tensors(tensor operations)

**Basic operation**

`+`, `-`, `*`, `/`

In [23]:
# you can add values to a tensor using the addition operator
tensor = tf.constant([[10,7], [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [24]:
# Multiplication of tensor
tensor * 4

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 28],
       [12, 16]], dtype=int32)>

In [25]:
# Substraction of tensor
tensor - 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [1, 2]], dtype=int32)>

In [26]:
#  we can use the tensorflow built in function too
tf.multiply(tensor, 4)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 28],
       [12, 16]], dtype=int32)>

Timing tensor multiplication by python function and tensorflow function

In [27]:
# Set the seed for reproducibility
tf.random.set_seed(42)

# Generate a random array with shape (3, 4)
rand_array = tf.random.normal(shape=(1000000,))

%timeit rand_array * 12
%timeit tf.multiply(rand_array, 12)


48.9 µs ± 854 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
38.8 µs ± 504 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Matrix Multiplication

In machine learning, matrix multiplication is one of the most common tensor operation.

There are two rules our tensors(or matrices) need to fulfill if we're going to matrix multiply them:
  1. The inner dimensions must match
  2. The resulting matrix has the shape of the inner dimensions

In [28]:
#  matrix multiplication in tensorflow
tf.matmul(tensor, tensor)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [29]:
# matrix multiplcation with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [30]:
tensor.shape


TensorShape([2, 2])

In [48]:
# Create 2 tensor of (3,2)
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
y = tf.constant([[7, 8],
                 [9,10],
                 [11,12]])
X, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [49]:
# Try matrix multiplication of same size which is not possible
tf.matmul(X, y)

InvalidArgumentError: ignored

In [50]:
# Transpose matrix before multiplication if criteria not fulfilled
tf.matmul(X, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [51]:
X, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [52]:
tf.matmul(X, tf.reshape(y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

**The Dot Product**

Matrix multiplication is also referred to as the dot product

matrix multiplication can be performed using:
* `tf.matmul()`
* `tf.tensordot()`

In [53]:
X,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Perform the dot product to X and y (requires X or y to be transposed)
tf.tensordot(X, tf.transpose(y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# now transposing X
tf.tensordot(tf.transpose(X), y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# perform matrix multiplication
tf.matmul(tf.transpose(X),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# perform matrix multiplication
tf.matmul(X,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Changing the Datatype of Tensors

In [54]:
# create a new tensor with deafult datatypes
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [55]:
# create a new trnsors
C = tf.constant([2,3])
C.dtype

tf.int32

In [56]:
# change from float 32 to float 16
B = tf.cast(B, dtype= tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [57]:
# change from int 32 to int16
C = tf.cast(C, dtype= tf.int16)
C

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([2, 3], dtype=int16)>

### Aggregating tensors

Aggregating tensors= condensing them from multiple values down to a smaller amount of values.  

In [58]:
#  Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [59]:
# Get absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the folllowing forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of tensor
* Get the sum of tensor


In [62]:
# Create a tensor and find min, max , mean
tensor1 =  tf.constant(np.random.randint(0, 100, size=50))
tf.reduce_min(tensor1, axis=0), tf.reduce_max(tensor1, axis=0), tf.reduce_mean(tensor1, axis=0)

(<tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=49>)

In [63]:
# sum of tensor
tf.reduce_sum(tensor1)

<tf.Tensor: shape=(), dtype=int64, numpy=2450>

In [64]:
# Standard deviation and variance in tf
tf.math.reduce_std(tf.cast(tensor1, dtype=tf.float32)) , tf.math.reduce_variance(tf.cast(tensor1, dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=float32, numpy=31.791193>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1010.68>)

In [65]:
# other method
import tensorflow_probability as tfp

tfp.stats.variance(tensor1),

(<tf.Tensor: shape=(), dtype=int64, numpy=1010>,)

In [66]:
tensor1_float = tf.cast(tensor1, dtype=tf.float32)
tfp.stats.stddev(tensor1_float).numpy()

31.791193

Find the positional maximum and minimum

In [67]:
# min and max postion
tf.random.set_seed(42)
tsr1 = tf.random.uniform(shape=[50])
tsr1,tf.argmin(tsr1), tf.argmax(tsr1)

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=int64, numpy=42>)

In [68]:
# INdex on our largest value postion
tsr1[tf.argmax(tsr1)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [69]:
# find max value of tsr1
tf.reduce_max(tsr1)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

### Squeezing a tensor(removing all single dimension)


In [70]:
# create a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [71]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [73]:
G_squeezed = tf.squeeze(G)
G_squeezed, G.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([1, 1, 1, 1, 50]))

### One-hot encoding Tensors

In [74]:
# Create  a list of indices
list =[ 0,1,2,3] # could be red, green , blue , purple/

# one=hit coding our list of indices
tf.one_hot(list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [75]:
# Specify custom values for one hot encoding
tf.one_hot(list, depth=4, on_value="I love deep learning", off_value= "I like music")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love deep learning', b'I like music', b'I like music',
        b'I like music'],
       [b'I like music', b'I love deep learning', b'I like music',
        b'I like music'],
       [b'I like music', b'I like music', b'I love deep learning',
        b'I like music'],
       [b'I like music', b'I like music', b'I like music',
        b'I love deep learning']], dtype=object)>

### Squaring, log and squaree root

In [76]:
# create new tensor
H = tf.range(1,10)

In [77]:
# square root
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [79]:
# gives sqaure
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [80]:
# find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and NumPy  Compatibility

In [81]:
# Create a tensor directly from a NumPy array
J= tf.constant(np.array([3.,4.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  4., 10.])>

In [82]:
# Convert out tensor back to NumPy array
np.array(J), type(J.numpy)

(array([ 3.,  4., 10.]), method)

In [83]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [84]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,4.,5]))
tensor_J = tf.constant(tf.constant([3.,4.,5.]))
# Check their datatypes
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Finding access to GPU

> Go to Runtime> change runtime type > select GPU (only in google colab)

In [85]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [86]:
!nvidia-smi

Mon Jul  3 10:00:37 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P0    27W /  70W |    401MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------