### Import Tensorflow and NumPy

In [2]:
import tensorflow as tf
import numpy as np

### Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()

In [4]:
scalar = tf.constant([1])
scalar, scalar.ndim

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>, 1)

In [8]:
#  creating vector
vector = tf.constant([[1, 2], [3,4]])
vector, vector.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 2)

In [14]:
#  creating matrix and tensor
tensor = tf.constant([[[1,2,3],
                      [2,3,4,]],
                      [[2,3,4],
                       [3,4,5]]])
tensor, tensor.ndim

(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [2, 3, 4]],
 
        [[2, 3, 4],
         [3, 4, 5]]], dtype=int32)>,
 3)

### Find the shape, rank and size of the tensors you created above

In [18]:
tf.shape(tensor), tf.size(tensor), tf.rank(tensor)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=12>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>)

### Create two tensors containing random values between 0 and 1 with shapes[5, 300]

In [23]:
A = tf.random.uniform(shape=(5,300), minval=0., maxval=1.)
B =  tf.random.uniform(shape=(5,300), minval=0. , maxval=1.)
A, B

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.9018984 , 0.669407  , 0.48460495, ..., 0.35147524, 0.7033843 ,
         0.57676923],
        [0.11806846, 0.31062424, 0.253502  , ..., 0.36740494, 0.1297462 ,
         0.31250954],
        [0.23188925, 0.1587987 , 0.9680431 , ..., 0.7827463 , 0.46035588,
         0.39493203],
        [0.07844651, 0.7007053 , 0.8945378 , ..., 0.8348323 , 0.01377416,
         0.7351649 ],
        [0.23217237, 0.79255414, 0.46831238, ..., 0.71184015, 0.7225778 ,
         0.05895364]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68389606, 0.7915503 , 0.96892595, ..., 0.876086  , 0.50657856,
         0.5942981 ],
        [0.02345681, 0.3249899 , 0.7196132 , ..., 0.00836945, 0.68608856,
         0.847317  ],
        [0.13446248, 0.71515846, 0.15934062, ..., 0.8515812 , 0.7665423 ,
         0.6008364 ],
        [0.19216192, 0.3397684 , 0.10772812, ..., 0.10847747, 0.8878504 ,
         0.4214332 ],
        [0.57740

### Multiplying tensors created above

In [25]:
tf.matmul(tf.transpose(A), B)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[0.7998859 , 1.044127  , 1.0670176 , ..., 1.2120131 , 0.901846  ,
        0.84085405],
       [1.0787147 , 1.3216658 , 1.1872354 , ..., 1.5338984 , 1.6939529 ,
        1.1624371 ],
       [0.9098318 , 1.6626463 , 1.0292197 , ..., 1.7815586 , 2.1907818 ,
        1.5268314 ],
       ...,
       [0.9256816 , 1.5457089 , 1.0120871 , ..., 1.7270199 , 2.1286986 ,
        1.4417444 ],
       [0.9658505 , 1.2420917 , 1.0451212 , ..., 1.6796643 , 1.1732011 ,
        0.91128576],
       [0.6301949 , 1.1155604 , 0.9418008 , ..., 0.9785488 , 1.4916329 ,
        1.1629143 ]], dtype=float32)>

### Multiply and get dot product

In [29]:
tf.tensordot(tf.transpose(A), B, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[0.7998859 , 1.044127  , 1.0670176 , ..., 1.2120131 , 0.901846  ,
        0.84085405],
       [1.0787147 , 1.3216658 , 1.1872354 , ..., 1.5338984 , 1.6939529 ,
        1.1624371 ],
       [0.9098318 , 1.6626463 , 1.0292197 , ..., 1.7815586 , 2.1907818 ,
        1.5268314 ],
       ...,
       [0.9256816 , 1.5457089 , 1.0120871 , ..., 1.7270199 , 2.1286986 ,
        1.4417444 ],
       [0.9658505 , 1.2420917 , 1.0451212 , ..., 1.6796643 , 1.1732011 ,
        0.91128576],
       [0.6301949 , 1.1155604 , 0.9418008 , ..., 0.9785488 , 1.4916329 ,
        1.1629143 ]], dtype=float32)>

Create a tensor with random values between 0 and 1 with shape [224, 224, 3]

In [30]:
tf.random.set_seed(42)
C = tf.random.uniform(shape=(224, 224, 3), minval=0., maxval=1.)
C

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635],
        ...,
        [0.42612267, 0.09686017, 0.16105258],
        [0.1487099 , 0.04513884, 0.9497483 ],
        [0.4393103 , 0.28527975, 0.96971095]],

       [[0.73308516, 0.5657046 , 0.33238935],
        [0.8838178 , 0.87544763, 0.56711245],
        [0.8879347 , 0.47661996, 0.42041814],
        ...,
        [0.7716515 , 0.9116473 , 0.3229897 ],
        [0.43050945, 0.83253574, 0.45549798],
        [0.29816985, 0.9639522 , 0.3316357 ]],

       [[0.41132426, 0.2179662 , 0.53570235],
        [0.5112119 , 0.6484759 , 0.8894886 ],
        [0.42459428, 0.20189774, 0.85781324],
        ...,
        [0.02888799, 0.3995477 , 0.11355484],
        [0.68524575, 0.04945195, 0.17778492],
        [0.97627187, 0.79811585, 0.9411576 ]],

       ...,

       [[0.9019445 , 0.27011132, 0.8090267 ],
        [0.32

### Find Min and max along axis 1 

In [34]:
tf.reduce_min(C, axis=1), tf.reduce_max(C, axis=1)

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[3.08728218e-03, 3.35657597e-03, 3.03745270e-04],
        [2.07266808e-02, 4.31776047e-04, 1.91926956e-04],
        [1.14024878e-02, 1.01062059e-02, 6.09242916e-03],
        [4.06265259e-04, 6.21199608e-03, 3.45444679e-03],
        [6.39915466e-03, 8.58688354e-03, 1.44493580e-03],
        [1.61790848e-03, 1.22084618e-02, 1.14864111e-02],
        [4.93729115e-03, 1.96862221e-03, 8.63945484e-03],
        [1.54995918e-03, 4.75943089e-03, 1.14287138e-02],
        [4.12750244e-03, 2.41160393e-03, 2.58970261e-03],
        [5.30874729e-03, 4.39548492e-03, 5.05447388e-04],
        [7.61234760e-03, 4.31275368e-03, 4.58204746e-03],
        [4.75323200e-03, 1.07632875e-02, 6.26456738e-03],
        [2.37929821e-03, 1.08909607e-03, 6.28829002e-04],
        [2.86233425e-03, 2.10285187e-04, 2.23445892e-03],
        [5.92350960e-04, 6.08563423e-04, 1.82008743e-03],
        [7.75337219e-03, 4.35113907e-03, 6.29305840e-04],
        [2.28178501e-

Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]

In [36]:
tf.random.set_seed(42)
D = tf.random.uniform(shape=[1,224,224,3])
D

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 ],
         [0.46448255, 0.03366041, 0.68467236],
         [0.74011743, 0.8724445 , 0.22632635],
         ...,
         [0.42612267, 0.09686017, 0.16105258],
         [0.1487099 , 0.04513884, 0.9497483 ],
         [0.4393103 , 0.28527975, 0.96971095]],

        [[0.73308516, 0.5657046 , 0.33238935],
         [0.8838178 , 0.87544763, 0.56711245],
         [0.8879347 , 0.47661996, 0.42041814],
         ...,
         [0.7716515 , 0.9116473 , 0.3229897 ],
         [0.43050945, 0.83253574, 0.45549798],
         [0.29816985, 0.9639522 , 0.3316357 ]],

        [[0.41132426, 0.2179662 , 0.53570235],
         [0.5112119 , 0.6484759 , 0.8894886 ],
         [0.42459428, 0.20189774, 0.85781324],
         ...,
         [0.02888799, 0.3995477 , 0.11355484],
         [0.68524575, 0.04945195, 0.17778492],
         [0.97627187, 0.79811585, 0.9411576 ]],

        ...,

        [[0.9019445 , 0.27011132, 

In [37]:
# Squeezing tensor
squeezed = tf.squeeze(D)
squeezed.shape

TensorShape([224, 224, 3])

Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [38]:
E = tf.constant([1,3,4,2,56,32,76,13,56,76])
tf.argmin(E), tf.argmax(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=6>)

One-hot encode the tensor 

In [40]:
encoded = tf.one_hot(E, depth=10)
encoded

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

# TensorFlow  quick start Example

### Load a dataset

In [45]:
mnist = tf.keras.datasets.mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train, X_test = X_train /255.0 , X_test /255.0


## Build a machine learning model:

In [47]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


In [51]:
prediction = model(X_train[:1]).numpy()
prediction

array([[ 0.5116496 , -0.07298739, -0.48650837,  0.529541  ,  0.17938587,
         0.31021136, -0.19557036,  0.1311414 , -0.52247053,  0.20945603]],
      dtype=float32)

`tf.nn.softmax`(predcitions).numpy()

In [53]:
tf.nn.softmax(prediction).numpy()

array([[0.14814746, 0.08256379, 0.05460089, 0.15082188, 0.1062659 ,
        0.12111856, 0.07303861, 0.10126086, 0.05267221, 0.10950986]],
      dtype=float32)

### define a loss function for training using losses.SparseCategoricalCrossenttropy

In [54]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [56]:
loss_fn(y_train[:1], prediction).numpy()

2.1109853

In [57]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

### Train and evalute  model

In [58]:
model.fit(X_train, y_train, epochs =5)

Epoch 1/5
1875/1875 [==============================] - 14s 7ms/step - loss: 0.2937 - accuracy: 0.9143
Epoch 2/5
1875/1875 [==============================] - 15s 8ms/step - loss: 0.1421 - accuracy: 0.9579
Epoch 3/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1060 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0867 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0751 - accuracy: 0.9767


In [59]:
model.evaluate(X_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0750 - accuracy: 0.9759 - 639ms/epoch - 2ms/step


[0.07501769065856934, 0.9758999943733215]

In [60]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [62]:
probability_model(X_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.98747351e-07, 2.48888412e-08, 1.18001284e-04, 1.10241126e-04,
        1.01984983e-11, 4.21656324e-07, 3.74005568e-13, 9.99763548e-01,
        6.40276426e-07, 6.28775342e-06],
       [1.72286914e-08, 1.32780960e-05, 9.99982953e-01, 2.99567296e-06,
        2.29175104e-17, 4.63009712e-07, 4.36566028e-09, 8.61137481e-11,
        3.43448221e-07, 2.01039746e-14],
       [5.85620796e-07, 9.98418331e-01, 3.04023906e-05, 2.32240814e-06,
        9.32491548e-06, 1.82807307e-05, 1.45097988e-06, 1.43438682e-03,
        8.42965092e-05, 5.60820240e-07],
       [9.99030590e-01, 2.21559290e-07, 5.29458455e-04, 6.22404787e-06,
        6.35987817e-07, 2.21415248e-05, 3.27545422e-04, 3.00397332e-05,
        9.91631282e-07, 5.22364171e-05],
       [1.50698661e-05, 9.91183470e-07, 8.56302067e-05, 2.19276011e-08,
        9.93575156e-01, 5.35537492e-06, 7.54706634e-05, 6.22694424e-05,
        2.67893756e-06, 6.17747894e-03]], dtype=float32)>