# Introduction to Numpy Fundamentals
* Creating arrays
* Numpy operations
* Dataframes
* Manipulating arrays

In [3]:
# Import NumPy as np
import numpy as np

In [4]:
# Create an 1d array
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [5]:
# Create 2d array
a2 = np.array([[1, 2, 3],[4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# create 3d array
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10,11,12]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
a3.shape

(2, 2, 3)

In [8]:
# shape , type, datatype, dimension, size 
a1.shape,  type(a1), a1.size , a1.ndim, a1.dtype

((3,), numpy.ndarray, 3, 1, dtype('int64'))

In [9]:
# attributes of a2
a2.shape, a2.size, a2.ndim, a2.dtype, type(a2)

((2, 3), 6, 2, dtype('int64'), numpy.ndarray)

In [10]:
# attributes of a3 
a3.shape, a3.size, a3.ndim, a3.dtype, type(a3)

((2, 2, 3), 12, 3, dtype('int64'), numpy.ndarray)

In [12]:
# Import panda as pd 
import pandas as pd

In [13]:
# create Dataframe from array
Df =  pd.DataFrame(a2)
Df

0  1  2
0  1  2  3
1  4  5  6

In [14]:
# random array of shape (10,2) of ones
randomarray = np.ones((10,2))
randomarray

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
# array of shape (7,2,3) of only zeroes
zeroarray = np.zeros((7,2,3))
zeroarray

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
# create random array within range 0-100) with step-3
randomarray = np.arange(0,100,3)
randomarray

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [17]:
# create a random array of numbers between 0 and 10 of size (7, 2)
randomarray1 = np.random.randint(0, 10, size=(7,2))
randomarray1

array([[5, 4],
       [2, 5],
       [3, 2],
       [2, 8],
       [6, 8],
       [4, 0],
       [9, 1]])

In [18]:
# create a random array of floats between 0 and 1 of size (3, 5)
randomarray3 = np.random.random((3,5))
randomarray3

array([[0.67467306, 0.00877296, 0.13158046, 0.37253664, 0.441476  ],
       [0.75554743, 0.30912251, 0.41192397, 0.20616428, 0.4687359 ],
       [0.23591901, 0.01805025, 0.51366312, 0.39937054, 0.67477798]])

In [19]:
# set seed 42 
# create random arraynumber between 0 and 10 of size (4,6)
np.random.seed(42)
randomarray4= np.random.randint(0,10 , size= (4, 6))
randomarray4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [20]:
# Create an array of random numbers between 1 & 10 of size (3, 7) and save it to a variable
array1 = np.random.randint(1, 10 , size=(3, 7))
array1 

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [21]:
# Find the 0'th index of the latest array you created
array1[0]

array([9, 1, 3, 7, 4, 9, 3])

In [22]:
# Get the first 2 rows of latest array you created 
array1[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [23]:
# Get the first 2 values of the first 2 rows of the Latest array
array1[:2, :2]

array([[9, 1],
       [5, 3]])

In [24]:
# Create a random array of numbers between 0 & 10 and an array of ones..both of size (3, 5), save them both to variables
random_array1 =  np.random.randint(0,10, size =(3,5))
ones1 = np.ones((3,5))
 


In [25]:
random_array1

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [54]:
ones1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
# add both arrays
variable = np.add(random_array1 , ones1)
variable

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [27]:
# add different shape arrays
ones2 = np.ones((5, 3))
new_var =ones2 + variable.T

In [28]:
# create array of ones of shapes (3,5)
ones3 = np.ones((3,5))

In [29]:
# substract ones array from latest
variable1 = np.subtract(new_var, ones3.T)

In [30]:
# multiply the ones array with the latest array
variable2 = np.multiply(variable1, ones3.T)

In [31]:
# take the latest array to the power of 2 using '**'
variable3 = variable2 ** 2
variable3

array([[ 49.,   4.,  36.],
       [ 64.,  64., 100.],
       [  9.,  16.,  16.],
       [  1.,   4.,  36.],
       [ 16.,  36.,   4.]])

In [32]:
variable4 = np.square(variable2)
variable4

array([[ 49.,   4.,  36.],
       [ 64.,  64., 100.],
       [  9.,  16.,  16.],
       [  1.,   4.,  36.],
       [ 16.,  36.,   4.]])

In [33]:
# Find the mean of the latest array
np.mean(variable4)

30.333333333333332

In [35]:
# find the maximum of array
np.max(variable4)

100.0

In [36]:
# find the min of array
np.min(variable4)

1.0

In [37]:
# find the std deviation of the latest array
np.std(variable4)

27.781688613585434

In [38]:
# find the variance
np.var(variable4)

771.8222222222226

In [39]:
# reshape the latest array to (3,5,1)
reshaped = np.reshape(variable4, (3,5,1))
reshaped

array([[[ 49.],
        [  4.],
        [ 36.],
        [ 64.],
        [ 64.]],

       [[100.],
        [  9.],
        [ 16.],
        [ 16.],
        [  1.]],

       [[  4.],
        [ 36.],
        [ 16.],
        [ 36.],
        [  4.]]])

In [40]:
# reshape the latest array by transpose
reshaped.T

array([[[ 49., 100.,   4.],
        [  4.,   9.,  36.],
        [ 36.,  16.,  16.],
        [ 64.,  16.,  36.],
        [ 64.,   1.,   4.]]])

In [41]:
# create two arrays of (3,3) and (3,5)
A1 = np.random.randint(0,10, size=(3,3))
A2 = np.random.randint(0,10,size=(3,2))

In [42]:
# dot product of two arrays
np.dot(A1, A2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [43]:
#create two arrays of random integers of same size
A3 = np.random.randint(0,10, size=(4,3)) 
A4 = np.random.randint(0,10, size=(4,3))

In [44]:
# perform dot product on latest 
np.dot(A3, A4.T)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

In [45]:
# compare the two arrays
A3 > A4

array([[False,  True,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True,  True]])

In [46]:
# Find which element of the first array is greater than 7
A3 > 7

array([[False,  True, False],
       [ True, False, False],
       [False, False, False],
       [False, False, False]])

In [47]:
# which part of each array is equal
A3 == A4

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [48]:
# sort one array
np.sort(A3)

array([[0, 6, 8],
       [0, 7, 8],
       [2, 7, 7],
       [0, 2, 7]])

In [49]:
# sort the indexes of one array
np.argsort(A3)

array([[0, 2, 1],
       [2, 1, 0],
       [2, 0, 1],
       [0, 2, 1]])

In [50]:
# find the index with minumum and maximum value in one of the arrays
np.argmin(A3), np.argmax(A3)

(0, 1)

In [51]:
# Find the indexes with the maximum values down the 1st axis (axis=1) of one of the arrays you created
np.argmax(A3, axis=1)

array([1, 0, 0, 1])

In [92]:
# Find the indexes with the minimum values across the 0th axis (axis=0) of one of the arrays you created
np.argmin(A3, axis=1)

array([0, 2, 2, 0], dtype=int64)

In [52]:
# create an array of normally distributed random numbers
array123 = np.random.normal(0, 1, size=(10,))
array123

array([-0.17773212, -0.41038331,  1.17971634, -0.89820794,  0.83479542,
        0.29656138, -1.03782988, -0.07580375,  0.97296353,  0.79559546])

In [53]:
# create an array with evenly spaced number between 1 and 100
new_var1 = np.linspace(1, 100, 10)
new_var1

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])